// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjSAB_mvJdg3OucsB1FudJ04mUKx-Rw2A',
    appId: '1:460281868223:web:cda32d0b440ac0157b3b0a',
    messagingSenderId: '460281868223',
    projectId: 'segfaulters-b8207',
    authDomain: 'segfaulters-b8207.firebaseapp.com',
    storageBucket: 'segfaulters-b8207.firebasestorage.app',
    measurementId: 'G-RF38XY4SFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVC0Z95-hw8bKhsJ82uRUIAM_9qfuHlz4',
    appId: '1:460281868223:android:0859442458d185c07b3b0a',
    messagingSenderId: '460281868223',
    projectId: 'segfaulters-b8207',
    storageBucket: 'segfaulters-b8207.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEldWehUuTYn3F0C299c761KiUqDPfzvI',
    appId: '1:460281868223:ios:be989f787b413af17b3b0a',
    messagingSenderId: '460281868223',
    projectId: 'segfaulters-b8207',
    storageBucket: 'segfaulters-b8207.firebasestorage.app',
    iosBundleId: 'com.example.segfaultersloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEldWehUuTYn3F0C299c761KiUqDPfzvI',
    appId: '1:460281868223:ios:be989f787b413af17b3b0a',
    messagingSenderId: '460281868223',
    projectId: 'segfaulters-b8207',
    storageBucket: 'segfaulters-b8207.firebasestorage.app',
    iosBundleId: 'com.example.segfaultersloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjSAB_mvJdg3OucsB1FudJ04mUKx-Rw2A',
    appId: '1:460281868223:web:28ee20aa159e9ffa7b3b0a',
    messagingSenderId: '460281868223',
    projectId: 'segfaulters-b8207',
    authDomain: 'segfaulters-b8207.firebaseapp.com',
    storageBucket: 'segfaulters-b8207.firebasestorage.app',
    measurementId: 'G-H90K9Y04EB',
  );
}
